services:
  tomcat:
    image: tomcat:9.0.58-jdk8-temurin-focal
    ports:
      - 8080:8080
    volumes:
      - $PWD/conf/tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml
      - $PWD/conf/context.xml:/tmp/context.xml
    command: '/bin/bash -c "mv /usr/local/tomcat/webapps /usr/local/tomcat/webapps2; mv /usr/local/tomcat/webapps.dist /usr/local/tomcat/webapps; cp /tmp/context.xml /usr/local/tomcat/webapps/manager/META-INF/context.xml; catalina.sh run"'

